module: default
runtime: custom
vm: true

api_version: 1
threadsafe: no

resources:
  cpu: 1.6
  memory_gb: 1.3

#Manual Scaling
manual_scaling:
 instances: 1

#Auto Scaling
# automatic_scaling:
#   min_num_instances: 2
#   max_num_instances: 20
#   cool_down_period_sec: 60
#   cpu_utilization:
#     target_utilization: 0.5

handlers:
- url: .*
  script: main.app
